
globalVariables(
  c(
    ".",
    "check_time",
    "date_checked",
    "get_counties",
    "get_states_current",
    "get_states_daily",
    "get_states_info",
    "get_tracker_urls",
    "get_us_current",
    "get_us_daily",
    "kind",
    "last_update",
    "name",
    "request_datetime",
    "ssl_no_verify",
    "state",
    "state_name",
    "states"
  )
)
